#!/bin/bash
#set -e
version="0.0.1"
progname=${0##*/}
echo "$progname"
echo "$version"
echo "Source:"
echo "https://codeberg.org/oSoWoSo/dialog"
BASIC=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "03 - basic:" 0 0 0 \
	update "update system" off \
	recommended "recommended packages" off \
	development "development tools" off 3>&1 1>&2 2>&3)
exitstatus=$?
REPO=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "04 - non-free and repositories:" 0 0 0 \
	repomu "void-repo-multilib" off \
	repono "void-repo-nonfree" off \
	repomn "void-repo-multilib-nonfree" off \
	nvidia "Nvidia proprietary drivers" off 3>&1 1>&2 2>&3)
exitstatus=$?
UI=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "05 - Choose user interface:" 0 0 0 \
	apps "Choose own apllications" off \
	de "Desktop environment" off \
	wm "Window manager and/or apps" off \
	minimal "Minimal xorg" off \
	xorg "Full xorg" off \
	wayland "Wayland" off 3>&1 1>&2 2>&3)
exitstatus=$?
DE=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "06 - Choose desktop environment:" 0 0 0 \
	budgie "budgie" off \
	cinnamon "cinnamon" off \
	enlightenment "enlightenment" off \
	gnome "gnome" off \
	gnomeapps "Install gnome applications" off \
	kde "kde plasma" off \
	kdeapps "Install kde appliacations" off \
	connect "Install kde connect" off \
	lumina "lumina" off \
	lxde "lxde" off \
	lxqt "lxqt" off \
	mate "mate" off \
	xfce "xfce" off 3>&1 1>&2 2>&3)
exitstatus=$?
WM=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "07 - Choose windows manager:" 0 0 0 \
	2bwm "Fast floating window manager" off \
	afterstep "Window Manager based on the look and feel of the NeXTStep interface" off \
	awesome "Highly configurable, next gen framework window manager for X" off \
	berry "Healthy, bite-sized window manager" off \
	blackboxwm "Stacking window manager for X11" off \
	bspwm "Tiling window manager based on binary space partitioning" off \
	byobu "Open source text-based window manager and terminal multiplexer" off \
	compiz "Compiz window manager meta-package" off \
	ctwm "Claude's Tab Window Manager" off \
	dvtm "Tiling window manager for the console" off \
	dwm "Dynamic window manager for X" off \
	evilwm "Minimalist window manager for the X Window System" off \
	fluxbox "Highly configurable and low resource X11 Window manager" off \
	fvwm "Extremely powerful ICCCM-compliant window manager" off \
	fvwm3 "Multiple large virtual desktop window manager" off \
	goomwwm "Get out of my way, Window Manager!" off \
	herbsluftwm "Manual tiling window manager for X" off \
	hikari "Stacking Wayland compositor with tiling features" off \
	i3 "Improved tiling window manager" off \
	i3-gaps "Improved tiling window manager - i3 fork with more features" off \
	icewm "Window Manager designed for speed, usability, and consistency" off \
	jwm "A light-weight window manager for the X11 Window System" off \
	mcwm "A minimalist stacking X window manager based on XCB" off \
	monsterwm "Minimal and lightweight dynamic tiling window manager" off \
	musca "Tiling window manager, with features nicked from ratpoison and dwm" off \
	mutter "Lightweight GTK+3 window manager" off \
	openbox "Standards compliant, fast, light-weight, extensible window manager" off \
	oroborus "A minimalistic window manager" off \
	pekwm "Window manager based on aewm++" off \
	qtile "A full-featured, hackable tiling window manager written and configured in Python" off \
	ratpoison "Window manager without mouse dependency" off \
	snapwm "Minimal and lightweight dynamic tiling window manager" off \
	sowm "Itsy bitsy floating window manager" off \
	spectrwm "Small dynamic tiling window manager for X11" off \
	subtle "Manual tiling window manager" off \
	sway "Tiling Wayland compositor compatible with i3" off \
	swm "A simple window manager" off \
	tinywm "Ridiculously tiny window manager" off \
	tmuxc "Local and remote tmux window manager" off \
	twm "Tab Window Manager for the X Window System" off \
	uwm "The ultimate window manager" off \
	vtwm "Virtual tab window manager" off \
	wayfire "3D wayland compositor" off \
	weston "Reference implementation of a Wayland compositor" off \
	wm2 "a simple window manager for X" off \
	wmderlan "Tiling window manager" off \
	wmfs "Window Manager From Scratch" off \
	wmii "Lightweight, dynamic window manager for X11" off \
	wmx "Simple window manager for X" off \
	xfwm4 "Next generation window manager for Xfce" off \
	xmonad "Tiling window manager fully configurable in Haskell" off \
	yeahwm "Window manager for X based on evilwm and aewm" off 3>&1 1>&2 2>&3)
exitstatus=$?
SHELL=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "08 - Choose shell:" 0 0 0 \
	bash "GNU Bourne Again Shell" off \
	fish "User friendly shell intended mostly for interactive use" off \
	zsh "Z shell" off 3>&1 1>&2 2>&3)
exitstatus=$?
DM=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "09 - Choose display manager:" 0 0 0 \
	cdm "cdm - Console Display Manager" off \
	emptty "emptty - Dead simple Display Manager running in CLI as TTY login" off \
	gdm "gdm - GNOME Display Manager" off \
	lightdm "lightdm - Light Display Manager" off \
	lxdm "lxdm - GUI login manager for LXDE" off \
	nodm "nodm - Minimalistic display manager for automatic logins" off \
	sddm "sddm - QML based X11 display manager" off \
	slim "slim - Desktop-independent graphical login manager for X11" off \
	stdm "stdm - Simple terminal display manager" off \
	xdm "xdm - X Display Manager" off 3>&1 1>&2 2>&3)
exitstatus=$?
TERMINAL=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "10 - Choose terminal emulator:" 0 0 0 \
	alacritty "alacritty" off \
	aminal "aminal" off \
	aterm "aterm" off \
	cool-retro-term "cool-retro-term" off \
	fbterm "fbterm" off \
	foot "foot (wayland)" off \
	gnome-terminal "gnome-terminal" off \
	kitty "kitty" off \
	konsole "konsole" off \
	lilyterm "lilyterm" off \
	lxterminal "lxterminal" off \
	mate-terminal "mate-terminal" off \
	qterminal "qterminal" off \
	roxterm "roxterm" off \
	rxvt-unicode "rxvt-unicode" off \
	sakura "sakura" off \
	terminal "terminal" off \
	terminator "terminator" off \
	terminology "terminology" off \
	tilix "tilix" off \
	xfce-terminal "xfce-terminal" off \
	xiate "xiate" off \
	xterm "xterm" off \
	yakuake "yakuake" off 3>&1 1>&2 2>&3)
exitstatus=$?
EDITOR=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "11 - Choose console text editor:" 0 0 0 \
	emacs "emacs" off \
	micro "micro" off \
	nano "nano" off \
	vim "vim" off 3>&1 1>&2 2>&3)
exitstatus=$?
GEDITOR=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "12 - Choose graphical text editor:" 0 0 0 \
	atom "atom" off \
	bluefish "bluefish" off \
	code-oss "code-oss" off \
	emacs "emacs" off \
	geany "geany" off \
	gedit "gedit" off \
	gvim "gvim" off \
	gvim-huge "gvim-huge" off \
	kakoune "kakoune" off \
	kate "kate" off \
	leafpad "leafpad" off \
	mousepad "mousepad" off \
	neovim "neovim" off \
	notepoadqq "notepadqq" off \
	sublime "sublime" off \
	vile "vile" off \
	zile "zile" off 3>&1 1>&2 2>&3)
exitstatus=$?
BROWSER=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "13 - Choose browser:" 0 0 0 \
	badwolf "badwolf" off \
	chromium "chromium" off \
	falkon "falkon" off \
	firefox "firefox" off \
	firefox-esr "firefox-esr" off \
	qutebrowser "qutebrowser" off 3>&1 1>&2 2>&3)
exitstatus=$?
MEDIA=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "14 - Choose media player:" 0 0 0 \
	audacious "audacious" off \
	deadbeef "deadbeef" off \
	moc "moc" off \
	mplayer "mplayer" off \
	mpv "mpv" off \
	parole "parole" off \
	qmmp "qmmp" off \
	rage-player "rage-player" off \
	strawberry "strawberry" off \
	totem "totem" off \
	vlc "vlc" off \
	xnoise "xnoise" off 3>&1 1>&2 2>&3)
exitstatus=$?
NETWORK=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "15 - Choose networking options:" 0 0 0 \
	connman "connman" off \
	cmst "connman qt" off \
	conngtk "connman gtk" off \
	connncurses "connman ncurses" off \
	conntray "connman tray" off \
	networkmanager "NetworkManager" off \
	nmgtk "NetworkManager gtk applet" off \
	nmplasma "NetworkManager plasma applet" off \
	nmqt "NetworkManager qt applet" off 3>&1 1>&2 2>&3)
exitstatus=$?
VIRT=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "16 - Choose virtualization options:" 0 0 0 \
	aqemu "aqemu" off \
	barrier "barrier" off \
	passthrough "PCI passthrough" off \
	qemu "qemu" off \
	qemu-ga "qemu guest agent" off \
	virt-manager "virt-manager" off \
	vbox "virtualbox" off \
	vbox-guest "viartualbox guest utilities" off 3>&1 1>&2 2>&3)
exitstatus=$?
BACKUP=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "17 - Choose backup:" 0 0 0 \
	borg "borg" off \
	dejadup "dejadup" off \
	timeshift "timeshift" off 3>&1 1>&2 2>&3)
exitstatus=$?
MISC=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --separate-output --checklist "18 - Miscellaneous options:" 0 0 0 \
	fonts "liberation, dejavu, ubuntu and roboto fonts" off \
	alsa-utils "Advanced Linux Sound Architecture" off \
	blueman "GTK+ Bluetooth Manager" off \
	bluez "Bluetooth tools and daemons" off \
	cronie "Runs specified programs at scheduled times" off \
	cups "Common Unix Printing System" off \
	cupsgui "CUPS printer configuration tool and status applet" off \
	gimp "GNU image manipulation program" off \
	inkscape "Vector-based drawing program" off \
	libreoffice "Productivity suite" off \
	nfs-utils "Network File System utilities" off \
	pulseaudio "Featureful, general-purpose sound server" off \
	tlp "Advanced power management tool for Linux" off \
	xkeylang "Choose X keyboard language" off \
	service "Enable required services" off \
	startdm "Start installed display manager" off 3>&1 1>&2 2>&3)
exitstatus=$?
INSTALL=$(dialog --backtitle 'universal void installer v0.0.1 by oSoWoSo' --title uvi --no-shadow --menu "19 - Install:" 0 0 0 \
	ask "Ask part again" \
	install "Install" \
	exit "Quit $progname" 3>&1 1>&2 2>&3)
exitstatus=$?
echo "$BASIC"
echo "$REPO"
echo "$UI"
echo "$DE"
echo "$WM"
echo "$SHELL"
echo "$DM"
echo "$TERMINAL"
echo "$EDITOR"
echo "$GEDITOR"
echo "$BROWSER"
echo "$MEDIA"
echo "$NETWORK"
echo "$VIRT"
echo "$BACKUP"
echo "$MISC"
echo "$INSTALL"